name: Publish
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  setup:
    name: python
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-groups
      - name: Build wheel
        run: uv build
      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
